### ISSUE TITLE
Lollipop elevation disable shadow

### ISSUE THREAD

**Issue by JV-TM** [shell-software/fab#12]
Hello,
I would like to add your FAB to "over a edge of two materials". Iam using relative layout with negative margin. And FAB shadow is shown properly. Problem is that when other views has android:elevation set, it shows over FAB and FAV is not visible. So, I add elevation (higher) to FAB. FAB is shown correctly over other view, but without shadow.
Any idea what I did wrong? Or how to solve this? Thank you.
![fab_with_elevation](https://cloud.githubusercontent.com/assets/8640167/6350567/58f74eb6-bc35-11e4-84c1-c24d1f20d92e.png)
![fab_without_elevation](https://cloud.githubusercontent.com/assets/8640167/6350571/68a10898-bc35-11e4-9db7-e0f95169f607.png)

**Comment by vbaidak** [comment]
Hi,

In ActionButton, when you enable elevation, shadow parameter becomes
disabled and thus only elevation shadow is used.

In most cases the correct way is to use shadow instead of elevation,
because it is supported by API 9 and higher. I think there is an issue in
your layout with overlapping components. You may send me an example of your
layout and I will try to help you with it.

On the other hand, elevation must work as expected (remember that it works
only on Lollipop devices). If you are testing it on Lollipop and it doesn't
work, tell me and I will check this for you.

Have a nice day,

Best wishes,
Shell Software Inc.

**Comment by vbaidak** [comment]
Hi,

The issue with non-working elevation for Lollipop devices will be fixed the nearest time

Have a nice day

**Comment by vbaidak** [comment]
Fixed in version 1.0.5
Please check and let me know

**Comment by JV-TM** [comment]
Great thanks a lot (-: 
tested:
KitKat 4.4 OK (shadow defined by fab)
Lollipop 5 OK (shadow defined by standard elevation)

**Comment by vbaidak** [comment]
Great!

Best wishes,
Shell Software Inc.
