### ISSUE TITLE
Make fab appear when scrolling 

### ISSUE THREAD

**Issue by norrisboat** [shell-software/fab#17]
I want the fab to appear only when scrolling

**Comment by vbaidak** [comment]
Hi **laylizzle**,

In order to make it appear just call **show()** method on **ActionButton** object.

Any _ScrollListeneres_ won't be implemented in **ActionButton** library because of 2 things:
1. This is actually not the part of the _Floating Action Button_ library
2. There are many of scroll containers (not only stock android) so searching and implementing all of them is not a trivial task and indeed it is simpler to call **show()** and **hide()** instead of making all this stuff

**Comment by norrisboat** [comment]
Thanks
