### ISSUE TITLE
Hide FAB onScrollView

### ISSUE THREAD

**Issue by douglasscriptore** [shell-software/fab#24]
Hello ! How do I hide FAB to scroll the page ?

Thank you

**Comment by vbaidak** [comment]
Hi,

Call hide() method in your scroll listener.

To show it again, call show() method.

Best wishes,
Shell Software Inc.

**Comment by douglasscriptore** [comment]
I'm using RecyclerView used the setOnScrollLister if anyone has doubts below is the code I used .

```
 @Override
        public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
            super.onScrolled(recyclerView, dx, dy);
            float y = recyclerView.getY();
            if(dy == 0){
                fab.show();
            }else if (y > dy) {
                fab.show();
            }else{
                fab.hide();
            }
        }
    });
```

**Comment by vbaidak** [comment]
I'm not sure whether this should work correctly.

[**getY()**](https://developer.android.com/reference/android/view/View.html#getY%28%29) is actually an inherited method from [**android.view.View**](https://developer.android.com/reference/android/view/View.html) class, which returns the visual position of the RecyclerView.

In order to get this work, I suggest:
1. Define some limit scroll value (you may use constant for this)
2. Calculate the absolute Y-axis scroll change value
3. If this absolute Y-axis scroll change value >= limit scroll value --> show or hide the **ActionButton**

The sample code may look like this:

``` java
    @Override
    public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
        int scrollLimit = 4 // convert this value to density-dependent pixel
        boolean scrollLimitReached = Math.abs(dy) >= scrollLimit;
        if (scrollLimitReached) {
            boolean scrollUp = dy >= 0;
            if (scrollUp) {
                actionButton.show();
            } else {
                actionButton.hide();
            }
        }
    }
```

Hope this helps. Good luck

**Comment by douglasscriptore** [comment]
wow great, thanks.

**Comment by vbaidak** [comment]
Issue solved
