### ISSUE TITLE
FAB position not exactly correct

### ISSUE THREAD

**Issue by asbozh** [shell-software/fab#30]
First of all thank you for this wonderful library. I tried it and it is working great but I noticed a small bug when I am using it with almost the default settings. The fab is upper and more to the left side than most of the Google native apps (Gmail, Keep, Photos..). It seems that the margin to the edges begins from the end of the shadows instead of the exact button. When I enabled elevation (which automatically disables shadows) the fab is located correctly at the exact same spot as the Google apps.

Here is some screenshots if my explanation wasn't good enough :)

FAB with the default settings
Here is the XML code with RelativeLayout

```
<com.software.shell.fab.ActionButton
    android:id="@+id/action_button"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_alignParentBottom="true"
    android:layout_alignParentRight="true"
    android:layout_marginRight="@dimen/fab_margin"
    android:layout_marginBottom="@dimen/fab_margin"
    fab:button_color="@color/fab_material_blue_500"
    fab:button_colorPressed="@color/fab_material_blue_900"
    fab:image="@drawable/fab_plus_icon"
    fab:rippleEffect_enabled="true"
    fab:show_animation="@anim/fab_scale_up"
    fab:hide_animation="@anim/fab_scale_down" />
```

![screenshot_2015-06-04-11-22-41](https://cloud.githubusercontent.com/assets/12729014/7981512/26240570-0ab8-11e5-9dc2-ec26c4061a41.jpg)

Here is a screenshot from Gmail app

![67ef57d0-9d95-4577-b7aa-b05e581d0f49 1](https://cloud.githubusercontent.com/assets/12729014/7981569/8567c01c-0ab8-11e5-96be-dd1fe7053673.jpg)

And here is a screenshot from FAB button with the same XML code but with added elevation in java code:
        if (Build.VERSION.SDK_INT >=21) {
            actionButton.setElevation(10);
        }

![screenshot_2015-06-04-02-41-54](https://cloud.githubusercontent.com/assets/12729014/7981633/d53e5ed4-0ab8-11e5-8559-caca948cc8f2.jpg)

**Comment by vbaidak** [comment]
Hi **asbozh**,

Thank you.
This is the desired behavior.

If you refer **ActionButton** [documentation](https://github.com/shell-software/fab) you can find there an explanation of the **Shadow Responsive Effect**, which is enabled by default:

> Note, that having Shadow Responsive Effect enabled leads to increasing of the ActionButton general view size. In this case view size calculated based on the maximum value of the shadow radius. This means, that event if there is a place near the ActionButton unfilled, it is actually used by Shadow Responsive Effect

That is, if you have it enabled the additional margin space is added. It is used by **Shadow Responsive Effect**, so that when shadow is increasing (**PRESSED** state) these spaces are filled with shadow.

If there were no space, in case when **ActionButton** is pressed and **Shadow Responsive Effect** enabled, it will be moved in an unexpected way (instead of just increasing the shadow).

So far as there is no possibility to draw the shadow outside the **View** this is the only solution to implement **Shadow Responsive Effect** for pre-Lollipop devices. 

May be in future **Google** will provide a more convenient way to apply elevation using _compat_ library, but this is not yet available.

So in your case I suggest you either to disable **Shadow Responsive Effect** or change the offset values (like in your screens).

**Comment by asbozh** [comment]
Thanks.
