### ISSUE TITLE
Needs compatible method with new CoordinatorLayout.

### ISSUE THREAD

**Issue by XinyueZ** [shell-software/fab#31]
Hi, 

it should be nice that the new CoordinatorLayout of design-lib gives behavior-relationship to your "fab" instead the FAB of design-lib self. I've tried but it throws exception to cast fab to FAB of design-lib.  With the behavior we can move the "fab" up automatically against Snackbar of design-lib.

**Comment by vbaidak** [comment]
Hi **XinyueZ**,

There is no possibility to perform such cast because this is how Java works

Despite the fact that classes [**com.software.shell.fab.ActionButton**](https://github.com/shell-software/fab/blob/master/fab/src/main/java/com/software/shell/fab/ActionButton.java) and [**android.support.design.widget.FloatingActionButton**](http://developer.android.com/reference/android/support/design/widget/FloatingActionButton.html) both extends [**android.view.View**](https://developer.android.com/reference/android/view/View.html) class they can't be casted to each other because no one of them is the superclass of the other and vice versa. In this case you'll get [java.lang.ClassCastException](http://docs.oracle.com/javase/7/docs/api/java/lang/ClassCastException.html). Always.

There are no plans to extend the [**com.software.shell.fab.ActionButton**](https://github.com/shell-software/fab/blob/master/fab/src/main/java/com/software/shell/fab/ActionButton.java) class from [**android.support.design.widget.FloatingActionButton**](http://developer.android.com/reference/android/support/design/widget/FloatingActionButton.html) in order to "make" it work with the new layouts. Furthermore, looking ahead I can say that starting from version **2.0.0** [**com.software.shell.fab.ActionButton**](https://github.com/shell-software/fab/blob/master/fab/src/main/java/com/software/shell/fab/ActionButton.java) will be extended from [**android.view.SurfaceView**](http://developer.android.com/reference/android/view/SurfaceView.html) class, which in turn extends the [**android.view.View**](https://developer.android.com/reference/android/view/View.html) class

So for your case you have 2 choices:
1. Use the [**com.software.shell.fab.ActionButton**](https://github.com/shell-software/fab/blob/master/fab/src/main/java/com/software/shell/fab/ActionButton.java) **AS-IS** and fit it to the layout you are using. Use convenient **move** methods for this
2. Use the [**android.support.design.widget.FloatingActionButton**](http://developer.android.com/reference/android/support/design/widget/FloatingActionButton.html) from the android design support library

**Comment by XinyueZ** [comment]
nice to know.
