### ISSUE TITLE
Background of the button 

### ISSUE THREAD

**Issue by KanwalPrakashSingh** [shell-software/fab#41]
When I use the BIG type button, and place it over some view, I found that that there is a rectangular box (of white color by default) covering the view beneath, I couldn't find a way to remove it, how do i remove this ?

**Comment by vbaidak** [comment]
Hi.

Thank you for using **ActionButton** library.

This is not the expected behavior and indeed in usual cases there is no such issue

Please provide related information required for investigation:
- Code for a class, where **ActionButton** object instantiated
- Layout _xml_ file, where **ActionButton** described (if any)

Thank you
